### ISSUE TITLE
change my terrible variable name to something interpretable by others

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-Dataset-Production#2]
https://github.com/ECCO-GROUP/ECCO-Dataset-Production/blob/c08bec27debf0cbe1522b2394ca132abf340280e/aws/configs/product_generation_config.json#L93-L95

from "data_res" to "lat-lon grid resolution"

**Comment by DuncanBark** [comment]
Done. Updated other variable names to be more clear and specific (ex. model_data_dir -> model_output_dir, etc.)
