### ISSUE TITLE
fix target grid radius for lat-lon field generation

### ISSUE THREAD

**Issue by ifenty** [ECCO-GROUP/ECCO-Dataset-Production#3]
https://github.com/ECCO-GROUP/ECCO-Dataset-Production/blob/fea6b91c40ed3a98ba69d1fc26de8963537ba447/aws/gen_netcdf_utils.py#L337-L339

now is 
```
        # calculate effective radius of each target grid cell.  required for the bin
        # averaging
        target_grid_radius = np.sqrt(lat_lon_grid_area / np.pi).ravel()
```

which is very wrong.  make a field "target_grid_radius_factor" in the 'product_generation_config.json'

```
target_grid_radius = 0.5*np.sqrt(lat_lon_grid_area.ravel())*target_grid_radius_factor
```

make default value of "target_grid_radius_factor" = sqrt(2) =  1.414

**Comment by owang01** [comment]
@ifenty 
`target_grid_radius = 0.5*np.sqrt(lat_lon_grid_area.ravel())*target_grid_radius_factor`
Using square root of regular grid area and sqrt(2) as the default "target_grid_radius_factor" may not work for a grid where meridional and zonal grid lengths measured in meters are very different. For example, a grid has very different dx and dy (in degrees). Even for a regular grid where dx and dy are the same in degrees, the meridional grid length measured in meters can be much longer than the zonal grid length (in m) in high latitudes. For instance, at 80N the meridional grid length is more than 5 times longer than the zonal grid length. Therefore target_grid_radius would be too short for searching in the meridional direction. 

One alternative way is use the larger value of meridional and zonal grid lengths, multiplied by a factor slightly larger than one.

**Comment by ifenty** [comment]
Alternatively, we could fix it to be uniform radius everywhere on the
globe. V4r5 is going to map to a 1/2 degree grid, just like V4r4. We could
choose 110/2 km as the search radius, which would essentially be nearest
neighbor at low latitudes and at high latitudes it could average a few
cells together.
